# Generated by Django 3.0.8 on 2020-08-02 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Вид блюда')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='URL')),
                ('image', models.ImageField(blank=True, upload_to='category/images/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Вид блюда',
                'verbose_name_plural': 'Виды блюд',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Наименование блюда')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена')),
                ('image', models.ImageField(blank=True, upload_to='dish/images/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Блюдо',
                'verbose_name_plural': 'Блюда',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200, unique=True, verbose_name='Пункт')),
            ],
            options={
                'verbose_name': 'Пункт',
                'verbose_name_plural': 'Пункты',
                'ordering': ('address',),
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=200, unique=True, verbose_name='ФИО клиента')),
                ('client_number', models.CharField(max_length=50, unique=True, verbose_name='Телефон клиента')),
                ('client_mail', models.EmailField(max_length=254, verbose_name='Электронная почта клиента')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата заказа')),
                ('order_price', models.FloatField(verbose_name='Стоимость заказа')),
                ('status', models.BooleanField(default=False, verbose_name='Статус заказа')),
                ('dishes', models.ManyToManyField(to='WebFront.Dish')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebFront.Station')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ('date',),
            },
        ),
    ]
