# Generated by Django 3.0.8 on 2020-08-06 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebFront', '0003_dish_grammers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='client_name',
            field=models.CharField(max_length=200, verbose_name='ФИО клиента'),
        ),
        migrations.AlterField(
            model_name='order',
            name='client_number',
            field=models.CharField(max_length=50, verbose_name='Телефон клиента'),
        ),
    ]
